name: Mirror the Github organization repos to Gitee

on:
  schedule:
    - cron: '0 7 * * 1' #设置定时任务
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
    - name: Git Env
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git config --global http.postBuffer 524288000
    - name: Mirror the Github organization repos to Gitee
      uses: Yikun/hub-mirror-action@v0.10
      with:
        src: github/Gladtbam
        dst: gitee/sakura_bot
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        white_list: "OpenWRT_Action"
