name: Github Mirrors to Gitee

on:
  push:
      branches:
      - main
  watch:
    types: started
  schedule:
      - cron: '0 7 * * 1'

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
#        - name: Checkout
#          uses: actions/checkout@v2.3.3
#          with:
#                fetch-depth: 0

        - name: Mirrors
          run: |
            git config --global user.email "github-actions@github.com"
            git config --global user.name "github-actions"
            git config --global http.postBuffer 524288000
            git clone https://gitee.com/sakura_bot/open-wrt_-action.git
            cd open-wrt_-action
            git remote rm origin
            git remote add origin https://sakura_bot:${{ secrets.GITEE_TOKEN }}@gitee.com/sakura_bot/open-wrt_-action.git
            git remote add upstream https://github.com/Gladtbam/OpenWRT_Action.git
            git fetch upstream
            git merge --all
            git push --all