name: Github Mirrors to Gitee

on:
  push:
      branches:
      - main
  watch:
    types: started
  schedule:
      - cron: '0 7 * * 1'

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.3
          with:
                fetch-depth: 0

        - name: Mirrors
          run: |
            echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
            git config --global user.email "github-actions@github.com"
            git config --global user.name "github-actions"
            git config --global http.postBuffer 524288000
            cd $GITHUB_WORKSPACE
            git remote -v
            git remote rm origin
            git remote add origin https://sakura_bot:${{ secrets.GITEE_TOKEN }}@gitee.com/sakura_bot/OpenWRT_Action.git
            git add .
            git commit -m "${{ env.FILE_DATE }}提交"
            git push --all origin