name: Mirror the Github organization repos to Gitee

on:
  schedule:
    - cron: '0 7 * * 1' #设置定时任务
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Mirror the Github organization repos to Gitee
      uses: Yikun/hub-mirror-action@v0.10
      with:
        src: github/Gladtbam
        dst: gitee/sakura_bot
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        white_list: "OpenWRT_Action"
