name: Build TEST

on:
  repository_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'

env:
    REPO_BRANCH: mt7621

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Upload firmware to Gitee
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git config --global http.postBuffer 524288000
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        git clone -b $REPO_BRANCH https://github.com/Gladtbam/OpenWRT_Action openwrt/
        cd $GITHUB_WORKSPACE/
        touch secret.key
        echo "${{ secrets.KEY }}" >> secret.key
        chmod 777 $GITHUB_WORKSPACE/usign
        ./usign -S -m $GITHUB_WORKSPACE/openwrt/packages/*/base/Packages -s secret.key
        ./usign -S -m $GITHUB_WORKSPACE/openwrt/packages/*/freifunk/Packages -s secret.key
        ./usign -S -m $GITHUB_WORKSPACE/openwrt/packages/*/luci/Packages -s secret.key
        ./usign -S -m $GITHUB_WORKSPACE/openwrt/packages/*/packages/Packages -s secret.key
        ./usign -S -m $GITHUB_WORKSPACE/openwrt/packages/*/routing/Packages -s secret.key
        ./usign -S -m $GITHUB_WORKSPACE/openwrt/packages/*/telephony/Packages -s secret.key
        ./usign -S -m $GITHUB_WORKSPACE/openwrt/targets/*/*/packages/Packages -s secret.key
        git clone -b $REPO_BRANCH https://gitee.com/sakura_bot/OpenWRT_Action.git /opt/OpenWRT_Action_fork
        cd /opt/OpenWRT_Action_fork
        git remote rm origin
        git remote add origin https://sakura_bot:${{ secrets.GITEE_TOKEN }}@gitee.com/sakura_bot/OpenWRT_Action.git
        git checkout $REPO_BRANCH
        cp -rf $GITHUB_WORKSPACE/openwrt/* /opt/OpenWRT_Action_fork/
        git add .
        git commit -m "${{ env.FILE_DATA }}同步"
        git push --set-upstream origin $REPO_BRANCH